### ISSUE TITLE
Untranslated string

### ISSUE THREAD

**Issue by DominikNovosel** [m-i-n-a-r/birday#133]
![IMG_20220430_214236.jpg](https://user-images.githubusercontent.com/66269443/166120520-615c6dec-5db6-46ab-9a59-b450e61c0d38.jpg)

The string "Event type" is still in English when displaying the app in Croatian, and I can't seem to find it in the `hr` string file.

**Comment by m-i-n-a-r** [comment]
Well well, i just noticed that this string is not translated in half the translations. Nice. The string name is "event_type_hint". I didn't see it because i had to disable lint for missing translation. I'll "awfully translate" it in the develop branch, can you tell me a good croatian translation, while we're at it? 😄

**Comment by m-i-n-a-r** [comment]
Done in 616487c651cbfb6a53fb9826f0b9c6aa3688f90e. If the translation is fine for you, i'll close the issue 👍

**Comment by DominikNovosel** [comment]
Perfect! You can close it, the translation is fine.
