### ISSUE TITLE
After first time setup, user sees no birthdays and must import them manually on CardDAV only phones

### ISSUE THREAD

**Issue by vatonbero** [m-i-n-a-r/birday#140]
Hi there,

I have just tested something and it appears that birday is not importing CardDAV contacts when you install and start the app for the first time. Not sure if this is intended.

**How to produce**
- add an account only with CardDAV contacts to your phone with DAVx5. Make sure that no other contacts are available in phone, any other account etc.
- install birday from F-Droid
- start birday and complete first time setup (including app permissions for reading contacts)
- notice number of birthdays in birday app after initial setup

**What i expected**
After granting contacts permission, I expected to see my contacts birthdays after I granted contacts permission

**What happened instead**
I had to open birday settings and select manual import from the menu to import contacts

**Notice**
If this was done by design then change behaviour to prompt for contacts permission after user decides to import contacts manually?

**Comment by m-i-n-a-r** [comment]
Hi and thanks for taking the time to open this issue! 
Yep, this is by design. On one side, i ask the contacts permission immediately since it's written in the intro slides. If the permission is denied, i never ask it again until the user tries to import the contacts. On the other side, i don't import the contacts directly and without asking because not everyone wants to import them, and most importantly because the app uses the automatic Google Drive backup feature (if installed from Play Store of course) and the automatic import may be in conflict with the data restore from Google Drive. I agree with you that immediately asking for the contacts permission is not that important, but i would have to edit 20+ translations to change this behavior 😄 
Any advice is well appreciated, i'll see what i can do to improve it!

**Comment by vatonbero** [comment]
Thank you for your response!

Can you take into consideration the following:
- Opt-In for Google Drive backup (during initial setup)
- Import contacts either right away or opt-in during initial start

For second part, it think it should be self explanatory: most users will use birday to manage existing birthdays in contacts. It is not my intention to generalise but using a separate app for managing birthdays is not required anymore so that is the reason why it could be integrated with contacts storage to enable better UX.

Again, these are my 2c on the matter

**Comment by m-i-n-a-r** [comment]
I should have fixed this in v4.x.x. Feel free to reopen this issue if that's not the case
