### ISSUE TITLE
Ability to send SMS

### ISSUE THREAD

**Issue by kia1349** [m-i-n-a-r/birday#147]
please provide an option to :
1-Ability to send SMS to friends automatically on the specified date and time
2-Create a section as a SMS template to send different SMS to contacts , based on gender or type of relationship (formal or friendly)
3-support RTL
4-monthly calendar page and display birthdays in each month on a calendar page (not Google Calendar, etc.)

**Comment by m-i-n-a-r** [comment]
Hi there 😄 
1-The ability to send SMS requires many invasive permissions, and since i'm trying to keep the app simple and permission free (excluding the optional conctacts permission) i can't do that. 
2-Given the first point, i could add a section with different wishes and sentences, but it's quite hard to translate each sentence in 20+ different languages
3-If you mean right to left, could you elaborate? The app should already support it, at least partially. Feel free to open a separate issue.
4-There's already a similar issue. I'm working on a yearly overview screen, i should finish it after the new widget 👍

**Comment by m-i-n-a-r** [comment]
Closed while waiting for other responses or requests regarding this kind of feature
