### ISSUE TITLE
Allow hiding instead of deleting dates

### ISSUE THREAD

**Issue by neubland** [m-i-n-a-r/birday#16]
Usecase: I save birthdays in my contacts first. Whenever I pull the data from my contacts (because I added new data there) I have to delete some birthdays in birday which I don't want to be reminded about. If I could hide them instead of deleting, they wouldn't reappear after every sync. Right now I have to choose between deleting them in Birday everytime or deleting the data from my contacts completely. Neither are optimal solutions.

Thanks for the great app!

**Comment by m-i-n-a-r** [comment]
Yep, that's true. I'll try to find a smarter solution in future updated, thanks for the suggestion!

**Comment by m-i-n-a-r** [comment]
This use case is partially covered from the new "notification only for favorite events" option, which should notify the user only for the events in the favorites section. I can't do better simply because i couldn't find a realiable way to translate this in code, considering how the app and the database work. Of course, i accept every advice and i'll make sure to reopen the issue if i find a way to do exactly this!
