### ISSUE TITLE
Automatic import does not work

### ISSUE THREAD

**Issue by toas-koas** [m-i-n-a-r/birday#169]
[2022-10-23-10-41-10.am.log](https://github.com/m-i-n-a-r/birday/files/9846044/2022-10-23-10-41-10.am.log)
I give the app access to my contacts, but there is no single birthday imported.
it will only be displayed on birthdays when I import them manually via the settings.

Version 3.1.1
19-20221014-microG-taimen

**Comment by m-i-n-a-r** [comment]
There's no automatic import in v3.1.1 😄 that's why it doesn't work! If you take a look at the develop branch, i added an "auto import" option recently as part of an "experimental" section in the settings. This option will be disabled by default, but it will auto-import any new contact and event when you open the app if enabled!
