### ISSUE TITLE
Data and tap actions in main and favorite lists

### ISSUE THREAD

**Issue by ghoevil** [m-i-n-a-r/birday#204]
#### Now when i click the name on favorites list, it often popup note, can we change sth...?

- default click to show details

- add a note icon , and show notes popup when click it.

#### The bottom Navbar's color
- It's always in dark mode, no matter if you change it to light mode.

## More info on Home list
- Show years of person on home list

**Comment by m-i-n-a-r** [comment]
- The details are in the main list, but i could show them on long press, i'll see what i can do, same for the note icon. The favorite section is designed to easily see all the relevant information and quickly add/edit the note
- That's a design choice, and it's there since v1.0. The only exception is the "monet" accent, which implements Material You and take every color from the system, including the bottom navbar
- You can show the years and the countdown by long pressing on an item in the main list!

**Comment by m-i-n-a-r** [comment]
You can now open the details from the favorite screen as well by long pressing the item, time to close this issue 😄
