### ISSUE TITLE
Import from dates from contacts incomplete

### ISSUE THREAD

**Issue by bovergaauw** [m-i-n-a-r/birday#208]
Whenever I import events from my contacts, only a partial list of birthdays imported. Birthdays from new contacts are imported correctly, but those from older contacts seem to be skipped.

**Comment by m-i-n-a-r** [comment]
I didn't have this issue, how can i recreate it? What do you mean by "older contacts"? I've contacts from 5+ years ago and i can import them 😕

**Comment by bovergaauw** [comment]
Hi m-i-n-a-r,

Thanks for the rapid reply 👍👍👍

With older contacts O indeed mean contacts that I added a fair amount of time ago, even when I changed them recently. I tried re-entering the birthdays of some non-imported contacts, but that didn't change anything.

I studied the exported VCARDs of some of the missed contacts, but couldn't fin anything in particular. I'll keep searching and will keep you informed.

**Comment by m-i-n-a-r** [comment]
Thanks! I'll look into it as well. Can i ask you what device and Android version you're using?

**Comment by bovergaauw** [comment]
Samsung S9 SM-960F
Android 10, never rooted

**Comment by bovergaauw** [comment]
For information, I downgraded to version 3.1.1 and was able to import birthdays correctly.

**Comment by m-i-n-a-r** [comment]
So basicaly i need an Android 10 Samsung smartphone to test, maybe Samsung contacts works differently from other contacts app. I'll add the help needed tag, since i don't have one.
I changed the contacts import procedure to also import contacts with a name prefix/suffix, middlename and nickname from v4.x on. It works properly on each of my 3 test devices (android 10 Oneplus, 12 Samsung and 13 Pixel) so i had no clue of this bug 😞

**Comment by m-i-n-a-r** [comment]
Just released in the Play Store Beta channel (and here and on F-Droid in a few days)! I'll close this and other similar issues, but feel free to reopen it if this bug persists.
