### ISSUE TITLE
[FEATURE REQUEST] Scroll down for past events

### ISSUE THREAD

**Issue by TSGblue** [m-i-n-a-r/birday#220]
Hi, thanks for that great app.

I would be nice to have the ability of see past events greyed above the current today birthdays. So you can see recent past events scrolling down with the finger without needed to scroll up all the current year.

Thanks and regards.

**Comment by m-i-n-a-r** [comment]
Birday should contain a yearly timeline and is focused on events rather then event occurrences. I understand that this feature could help, even if there's a search field and the quick scroll is enabled. I'll see if i can add an option to enable some kind of "infinite scroll" in future updates, thanks for suggesting it!

**Comment by m-i-n-a-r** [comment]
I added a "recently missed" section in the quick apps bar, but the list can't be infinite and this feature should partially match your needs. Feel free to reopen if I'm wrong 😄

**Comment by KuechlerO** [comment]
Ping!
Great App!

Nevertheless I would like to draw the attention to this issue again.
I think this is a vital element.
My suggestion would be: 
The homepage-scrolling starts like it is right now, but one can also scroll up to inspect past birthdays (instead of the normal down scrolling, which reveals further future birthdays).
What do you think @m-i-n-a-r ?
