### ISSUE TITLE
Settings toggle buttons issue

### ISSUE THREAD

**Issue by VasilisKos** [m-i-n-a-r/birday#259]
They don't follow the Material You guidelines. Look at the screenshots and compare with Google Keep settings. They should be redesigned.

![Screenshot_20230420-152118](https://user-images.githubusercontent.com/12777771/233364903-12af7887-64fd-4797-a7c6-ca2f88650f55.png)

![Screenshot_20230420-152051](https://user-images.githubusercontent.com/12777771/233364937-5cc662ae-055a-4e93-a630-9389fdb0ac3d.png)

**Comment by m-i-n-a-r** [comment]
That's not completely true. They are indeed from Material 3 (you can see them in Google Clock and Android 13 settings, for example), but there's a second version of the same component, from Material Components. I chose this version because it's the only version supported in the android preference library. Here's a couple of links:

- [My question on Stack Overflow](https://stackoverflow.com/questions/73639187/new-android-12-materialswitch-and-androidx-preference)
- [The second version, from Material Components](https://m3.material.io/components/switch/overview)

Anyway, I'm waiting and I want to use the Material Components switches, but i can't do it everywhere in the app at the moment, and Google itself is rather confused about it (just download some Google apps, you'll find 3 different switch designs).
