### ISSUE TITLE
Vibration on key press still on in calendar mode

### ISSUE THREAD

**Issue by Nesaijn** [m-i-n-a-r/birday#26]
Even though I have the vibrations on press off, it still vibrates when picking a date. I also tried restarting the app.
Also shouldn't that be something that one should choose in the system settings? Maybe remove the option?

Xperia XA2
LineageOS 17.1 (Android 10)

**Comment by m-i-n-a-r** [comment]
Not every system manages the vibration for every app, or one have to activate the battery saver, so i put that option in. Regarding the vibration in the date picker, i have no control over that, since it's a material dialogs possible improvement, which i asked here https://github.com/afollestad/material-dialogs/issues/2021

**Comment by Nesaijn** [comment]
Oh, I see. Good thing you already know about the issue and try to solve it. :+1:
