### ISSUE TITLE
Export to csv

### ISSUE THREAD

**Issue by Nesaijn** [m-i-n-a-r/birday#28]
Exporting and maybe importing the entries in csv or txt files would be a nice to have.

**Comment by m-i-n-a-r** [comment]
Yep, i agree. I'll see what I can do!

**Comment by jakeisnt** [comment]
This is a bit specific to my workflow, but it would be excellent to be able to read from and export to an Org-mode file format as well! I'd be happy to work on this if there would be interest in adding such a feature.

**Comment by m-i-n-a-r** [comment]
I appreciate every help! Regarding this function, you already have a csv technically, since the exported file (I mean, the "Birday backup") can be opened using an SQLite browser and exported as csv. But I agree, a direct export excluding the useless columns would be great, but it's a bit hard. 

Regarding the import, i could only import a specific format of csv, i don't think I could automatically detect the right columns from any csv. But again, I appreciate any help and suggestion 😉

**Comment by m-i-n-a-r** [comment]
So, i tried to write a csv importer and exporter in f6115b8620d0b9d2bc21ee052efefd4071c6b837 and previous commits. It will be available in the next update under the "experimental settings". I made it in the smartest way possible, and it can recognize the fields automatically in certain cases, but it's away from perfect
