### ISSUE TITLE
New update?

### ISSUE THREAD

**Issue by saltsoftdrink** [m-i-n-a-r/birday#287]
Is any update coming it's been a long time there are no updates

**Comment by m-i-n-a-r** [comment]
Well, the good news is that I'm alive, the bad one is that I'm currently working on other projects BUT I should release a translation/library update in the next few weeks. I'm not sure if I will add new features though (there's nothing super requested at the moment).
Thanks for asking :)

**Comment by daoxi** [comment]
Hi @m-i-n-a-r, since you mentioned "translation/library update", would you be able to include the [recently opened pull request that brings Traditional Chinese (zh-rTW) translation to 100%](https://github.com/m-i-n-a-r/birday/pull/286) in that update?

**Comment by m-i-n-a-r** [comment]
Yep, no problem! Out of curiosity, you didn't use Crowdin because you have no access to it, or simply because you prefer the "classic" way of translating?

**Comment by herrbrixter** [comment]
@m-i-n-a-r I added a few feature requests. Please consider them. Thanks!

**Comment by m-i-n-a-r** [comment]
Yep, I'm replying. And, I'm late for the update 😄 Please be patient with me!

**Comment by m-i-n-a-r** [comment]
Yep: I'm terribly late, as you may have noticed 😄 
Many features are ready and I want to release a beta update, BUT there are 2 major bugs and I still can't fix them:

1. The widget configuration doesn't work on Android 14! The reason is explained in [this question](https://stackoverflow.com/questions/78585725/appwidget-configuration-activity-doesnt-start-in-android-14-missing-opt-in-by) i posted
2. I'm implementing the [predictive back gesture ](https://developer.android.com/design/ui/mobile/guides/patterns/predictive-back) and it doesn't work properly for some elements of the app (mostly the main navigation).

I can't release a beta until this 2 points are fixed and working. I'm working on it, but it will take time since the documentation is scarce. I understand that the last update is dated 1 year ago and I'm sorry, but I'm here and I'm still working on it 👍

**Comment by m-i-n-a-r** [comment]
Bugs fixed and beta released! If everything is fine, I'll release it in production and on F-Droid as well! Check crowdin if your first language isn't English and help me with the translation if you have a minute :)

**Comment by saltsoftdrink** [comment]
> Bugs fixed and beta released! If everything is fine, I'll release it in production and on F-Droid as well! Check crowdin if your first language isn't English and help me with the translation if you have a minute :)

My first language is English
