### ISSUE TITLE
[Feature request] Show age behind the birth-date - enhancement

### ISSUE THREAD

**Issue by Nordlicht-13** [m-i-n-a-r/birday#293]
On the homepage of the app with the birthdays, it would be nice to have the age next to the bith-date like:
John Doe
28.02.1973 (51)

And if the birthday is today or tomorrow, it would be nice to have a option to replace the date with today and tomorrow like:
Donald Duck
Today (76)

And if the date is next year it should be (77 in 2025)

**Comment by herrbrixter** [comment]
In addition to Today and Tomorrow, please also use the word Yesterday instead of yesterday's date.

**Comment by flori-s** [comment]
Hi, would it be possible for me to work on this issue?

**Comment by m-i-n-a-r** [comment]
> Hi, would it be possible for me to work on this issue?

Whoops sorry for the latte reply 😞 I'm already working on it and this is probably the last thing I'll do before releasing the update as a beta in Play Store. Any help is always appreciated on this and other issues though!

**Comment by m-i-n-a-r** [comment]
Ok, before I commit my changes and finish this, there's a couple of things I have to ask:

1. Should the age be the CURRENT age or the NEXT age?
2. Why have the "today" and "tomorrow" thing if those information are in the top card?
3. Last but not least, mixing date of births and countdowns (tomorrow, today etc.) is.. weird. Is it only me?

My idea (and what I did) so far was:
Put the CURRENT age (in the form "23-02-1990, 34 years") just like the favorite screen
Add the yesterday thing in the details screen

I don't know, let me know what you think 😄

**Comment by herrbrixter** [comment]
Hi,

I added a screenshot of another birthday app that I really like.

![Screenshot_2024-06-13-08-07-28-844_com marcow birthdaylist_1](https://github.com/m-i-n-a-r/birday/assets/31651148/acfc8e76-923f-4c50-b7ef-d317a0f94ff5)

1. Age when the birthday comes
2. The top card says the date in numerical format, right? Like Jun 15. So not in words like "today"
3. Like my screenshot, I like mixing "today" and "tomorrow" with other numerical dates. "Today" means today, but a date like "June 15" would only mean today if you know that the date today is June 15. Sometimes I don't know what day is it today.
4. I have no idea the long press existed. I would prefer if I didn't have to long press because the age and countdown are important, not nice to know.

Thanks for working on it!

**Comment by m-i-n-a-r** [comment]
This kind of view is available in the favorite screen, while in the main screen, my interest is keeping the layout extremely compact and accessible (believe it or not, Birday has a lot of senior users or users with hundred of entries 😄). I added the current age in the main list, and that's probably all, because adding anything else makes the lines too big with large to xlarge text sizes. So I'll close this for now, but thanks for your suggestions and feel free to comment if you have other advices 👍
