### ISSUE TITLE
[Feature request] Write entries directly to a calendar on the phone - enhancement

### ISSUE THREAD

**Issue by Nordlicht-13** [m-i-n-a-r/birday#295]
It would be nice if you could write the entries directly to a calendar on the phone you can choose on your own.
I have a separate calendar for the birthday entries, that are filled right now by EboBirthday. Really nice feature!

**Comment by m-i-n-a-r** [comment]
I already tried that, but I didn't find a way to do it. I'll try again!

**Comment by Nordlicht-13** [comment]
eboBirthday is adding a comment in the notes of the entrie in the calendar like:
The following stuff is for EboBirthday. Please do not delete! [EB:ID106]

Maybe this info helps.

**Comment by simonesestito** [comment]
IMHO, this is counterproductive in the app and should not be added for several reasons. Let me enumerate the most important ones:
1. It may create lots of conflicts and will require duplicate handling when importing from the calendar again in the future, after an export -- this can be the case of a user that today performs an export, after a few months adds an event to the calendar and then tries to do an import to add this new event to Birday 
2. Maybe the most significant: it may be against the app itself, since it could entice users to uninstall the app directly and just use the standard calendar app

**Comment by m-i-n-a-r** [comment]
I added a super-duper experimental export to calendar feature in the latest beta, and close this, feel free to re-open if it doesn't work as expected

**Comment by Nordlicht-13** [comment]
Where do I find this in beta? 
I installed it from f-droid.

**Comment by Nordlicht-13** [comment]
Found the option to write it to a calendar.
But I can't see this calendar with aCalendar.
Also it would be better, if you could choose the calendar you would like to write to. I have a birthday calendar on my nextcloud for that.
EboBirthday is writing into that like "Johne Does Birthday (58)".
Would love to see something like this in Birday.

**Comment by Nordlicht-13** [comment]
I installed Fossify Calendar to check this with another app.
In Fossify Calendar I can see the Birday-Calendar.
Entry is "John Doe - Birthday"
would be nice to have the possibility to edit this like:
$n - The Name
$s - The letter s, except after s
$e - The name of the event (birthday, anniversary)
$a - The age
