### ISSUE TITLE
[Feature request] Add ways to contact people on their birthday

### ISSUE THREAD

**Issue by breversa** [m-i-n-a-r/birday#296]
Hello and first of all thanks for this nice app! :)

I find it weird that Birday can show a nice animated notification on someone’s birthday, along with options to modify, cancel, share or add not to the birthady… but no option to directly *contact* the person to wish them a happy birthday ! ^^

For instance, a button to open the contacts list app, from which I can choose whichever way to contact them (or even navigate to their address).

**Comment by m-i-n-a-r** [comment]
Thanks for using Birday! There are a couple reasons for that 😄 
- Birday can import from contacts, but doesn't link the event to the contact. This is basically because Birday can be used without importing from contacts and is not a contacts app, so I have no way to open the contact details, and change this would basically require to rewrite the app from scratch
- Another approach would be to save the contacts details in Birday itself, but this is a privacy concern for many users. Furthermore, the ability to send an sms, call a number and so on requires additional permissions, and I'm trying to keep the number of permissions required the lowest possibile.

I understand that this can be a letdown, and I understand that the quick apps launcher feature may not be enough since it's "generic" but it's the only way to keep the app simple and clean. 😞
