### ISSUE TITLE
Change the notification format

### ISSUE THREAD

**Issue by para2ox** [m-i-n-a-r/birday#308]
## Suggestion
Please change or add the option to change the notification format to something like this:

**Title:**
[name]

**Description:**
[age] [when]

## Result
**John**
64 years in 7 days!
**John**
64 years today!
**John**
Birthday in 3 days! (if no year is specified)
ㅤ
Instead of
ㅤ
**Birday Reminder**
Today's events are: John, 64 years. Have a great day!
**Birday Reminder**
Upcoming events! John, 64 years

## Value
More informative and less cluttered output.

**Comment by m-i-n-a-r** [comment]
I'll see if I can add this to the "angry bird" mode, since the standard mode should remain simple and linear, to preserve the simplicity of use 😄 thanks for the suggestion!

**Comment by para2ox** [comment]
> I'll see if I can add this to the "angry bird" mode, since the standard mode should remain simple and linear, to preserve the simplicity of use 😄 thanks for the suggestion!

Correct me if I'm missing something, but doesn't my version look simpler? 🙂
I just saw in the issue #299 that the new version will have separate notifications for each birthday, so I thought that changing the format of the notifications now would be a good idea.

---
###### from
**Birday Reminder**
Today's events are: John, 64 years. Have a great day!

###### to
**John**
64 years today!

---
This way, the new version will be less cluttered (~Birday Reminder~, ~Have a great day!~) and the key information (name, age) will be visible at a quick glance. Moreover, if an additional notification appears, you'll be able to see how many days from now a person's birthday will be (64 years in 7 days!) — right now you have to open the app to find it out (Upcoming events! John, 64 years).

**Comment by Nordlicht-13** [comment]
See also
https://github.com/m-i-n-a-r/birday/issues/293
similar feature request.

**Comment by herrbrixter** [comment]
+1 for this idea. The current reminder just says "Upcoming" without saying when. It would be better to says "In 2 days"

**Comment by m-i-n-a-r** [comment]
So, after some commits, here's the situation:
- normal and additional notification, grouped, no angry bird mode (default)
![groupednoangry](https://github.com/m-i-n-a-r/birday/assets/8942111/9d04e18a-0d7e-46c2-8684-1fe6e282b42b)
- normal and additional notification, ungrouped, no angry bird mode
![ungroupednoangry](https://github.com/m-i-n-a-r/birday/assets/8942111/33b47aa6-7f19-40dd-97f7-ac02b13bc03a)
- normal and additional notification, grouped, angry bird mode
![groupedangry](https://github.com/m-i-n-a-r/birday/assets/8942111/3d0d3aa6-8fdf-4a05-a26a-6a47264922b0)
- normal and additional notification, ungrouped, angry bird mode
![ungroupedangry](https://github.com/m-i-n-a-r/birday/assets/8942111/673485e8-e75d-46ef-94f7-b184a33d6334)
Now, as you can see, I can't use the name in the title when the notifications are grouped simply because the grouped notification supports up to 3 events and the name should be a single line (Google guidelines..). I have to adjust some part of the text (remove "upcoming events!" when the event is today for example) but this is pretty much it. I'll make those adjustments and close the issue 😄
