### ISSUE TITLE
Sync with Contacts

### ISSUE THREAD

**Issue by GEkuL** [m-i-n-a-r/birday#43]
Hi!

You have made a nice app, thanks for it!

It could be an interesting idea to **synchronize your app with contacts**. Now as I know, the feature works for import from Contacts. How about **export to contacts?**

I think, it'd be really cool!

**Comment by m-i-n-a-r** [comment]
A similar feature could be very useful, but is indeed very hard to implement, and i don't even know if it's possible. I'll probably try to work on it in the future!

**Comment by m-i-n-a-r** [comment]
After some investigation, i think (as far as i know) i can't implement such feature, because it could potentially cause issues and i didn't find a way to add the events to the contacts app programmatically. Furthermore, adding a contact without a real "contact" (i mean, a phone number, an address and so on) is not so useful probably. Thanks for the request though, i'll make sure to reopen it if i discover something new!
