### ISSUE TITLE
Export to external storage doesn't work

### ISSUE THREAD

**Issue by mateusz-bak** [m-i-n-a-r/birday#79]
When clicking "export and share birthdays" the backup is supposed to be saved in Android/data/com.minar.birday/files. It is not saved there, there is not com.mindar.birday in Android/data. Backup can be exported to cloud eg. Nextcloud only it is not saved to phone's external storage.

App version 2.1.0 from F-Droid
Android 11
OnePlus 8T

**Comment by m-i-n-a-r** [comment]
Well, are you sure? I just tried to export my events, and i can find the file in internal storage/Android/data/com.minar.birday/files. I'm on a OnePlus 7 Pro running Android 11. Please describe everything you do to export the events and try again. If the problem is still there, i'll try again to recreate the issue. The only difference is that my Birday comes from the Play Store, but it shouldn't be a problem. 🤔

**Comment by mateusz-bak** [comment]
Weird, Im checking internal storage with default oneplus file manager and files by google. In internal storage in Android/data there is no com.minar.birday directory. How I export? Just go to Birday's settings and click "Export and share birthdays". There is a snackbar "expoer completed!" but I cannot find the backup. Maybe this is OnePlus' issue not the apps itself.

**Comment by m-i-n-a-r** [comment]
Well i tried again and again and it works on my devices. Furthermore, if the export fails, you can't even share the backup, because the file doesn't exist and can't be found. I'll investigate and reopen the issue for any update on this 👍 Thanks for letting me know!
